---

global:
  sendAnonymousUsage: false

providers:
  docker:
    exposedByDefault: false
    network: network.ss
  file:
    directory: /etc/traefik
    watch: true
  # kubernetesIngress:
  #   labelSelector: "traefik-ingress=traefik"
  #   ingressClass: "traefik-lb"
  #   ingressEndpoint:
  #     ip: 10.254.254.254
  #     # hostname: "host.docker.internal"

api:
  insecure: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: ':80'
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  websecure:
    address: ':443'

tls:
  certificates:
    - certFile: /etc/traefik/cert.pem
      keyFile: /etc/traefik/key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/cert.pem
        keyFile: /etc/traefik/key.pem

ping:
  entryPoint: 'web'

log:
  level: DEBUG

...
