version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.12  # Use an appropriate base image
        environment:
          DOCKER_DRIVER: overlay2
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          version: 26.0
          docker_layer_caching: true

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl make apt-utils net-tools procps iproute2 iputils-ping

      - run:
          name: Generate .env file
          command: make env

      - run:
          name: Start docker-compose services
          command: |
            docker-compose up -d

      - run:
          name: Test DNS Resolver with dig
          command: |
            dig @127.0.0.1 -p 53 any-domain.docker +short
            if [ $? -ne 0 ]; then
              echo "DNS resolution failed!"
              exit 1
            fi

      - run:
          name: Test DNS resolver with ping
          command: |
            ping -c 3 any-domain.docker
            if [ $? -ne 0 ]; then
              echo "Ping test failed!"
              exit 1
            fi

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
